"""Constants shared by more than one module. Business rules belong in policy.md, not here."""

MAX_ITERS = 3
RECURSION_LIMIT = 8
TOKEN_BUDGET_PER_TICKET = 20_000

HTTP_TIMEOUT_SECONDS = 10.0
HTTP_MAX_ATTEMPTS = 5
HTTP_BACKOFF_INITIAL_SECONDS = 30.0
HTTP_BACKOFF_MULTIPLIER = 2.0
HTTP_BACKOFF_MAX_SECONDS = 60.0
HTTP_RETRY_STATUS_CODES = frozenset({429, 500, 502, 503, 504})

LLM_TIMEOUT_SECONDS = 60.0

EMAIL_PLACEHOLDER = "<EMAIL_REDACTED>"
PHONE_PLACEHOLDER = "<PHONE_REDACTED>"
CARD_PLACEHOLDER = "<CARD_REDACTED>"
SSN_PLACEHOLDER = "<SSN_REDACTED>"

KNOWN_LANGCHAIN_ENDPOINTS = (
    "https://api.smith.langchain.com",
    "https://eu.api.smith.langchain.com",
)
